# Stage 1: Build static assets
FROM node:20-alpine AS builder

WORKDIR /app

# Copy dependency configs
COPY package*.json ./

# Install packages
RUN npm ci

# Copy sources
COPY esbuild.mjs ./
COPY assets/ ./assets/
COPY public_html/ ./public_html/
COPY src/ ./src/

# Compile Web UI
RUN npm run build

# Stage 2: Serve using Nginx
FROM nginx:alpine

# Copy built public_html static files
COPY --from=builder /app/public_html/ /usr/share/nginx/html/

# Copy Nginx template configuration for envsubst support
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

ENV BACKEND_URL=http://192.168.1.124:9091
ENV QBITTORRENT_URL=http://192.168.1.124:8080

EXPOSE 80

